# References and Further Reading

## Further reading

A good textbook that covers a lot of the same ground but in way more depth (and following a Bayesian approach) is [Statistical Rethinking](https://xcelab.net/rm/statistical-rethinking/) by Richard McElreath.

Check out the [online textbooks](https://psyteachr.github.io/) and resources that my group and University of Glasgow have been developing. There are great resources to learn more about data wrangling and visualization, among other things.

## Linear mixed-effects models

If you feel like you are still in need of a basic introduction to linear mixed-effects models, [Brown (2021)](https://journals.sagepub.com/doi/10.1177/2515245920960351) does a good job.

The classic on crossed random effects is [Baayen, Davidson, and Bates (2008)](https://doi.org/10.1016/j.jml.2007.12.005).

On specifying random effects structure, see [Barr, Levy, Scheepers, and Tily (2013)](https://doi.org/10.1016/j.jml.2012.11.001). [Barr (2013)](https://doi.org/10.3389/fpsyg.2013.00328) discusses factorial designs. [Matuschek et al. (2017)](https://doi.org/10.1016/j.jml.2017.01.001) argue against the 'keep it maximal' view and for data-driven random effects.

[Luke (2017)](https://link.springer.com/article/10.3758/s13428-016-0809-y) discusses the different ways to get p-values from a linear mixed-effects model and their advantages/disadvantages.

For a recent tutorial on simulating data with crossed random factors of subjects and stimuli, check out [Debruine and Barr (2021)](https://doi.org/10.1177%2F2515245920965119).

## References
